apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
---
apiVersion: v1
kind: Secret
metadata:
  name: payment
  namespace: roboshop
type: Opaque
data:
  AMQP_USER: cm9ib3Nob3AK
  AMQP_PASS: cm9ib3Nob3AxMjMK
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  # labels related to deployment resource
  labels:
    project: roboshop
    tier: backend
    component: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: backend
      component: payment
  # Pod
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: payment
    spec:
      containers:
      - name: payment
        image: joindevops/payment:4.0.0
        ports:
        - name: liveness-port
          containerPort: 8080
        startupProbe:
          httpGet:
            path: /health
            port: liveness-port
            # we are giving 5 minutes to start the application
          failureThreshold: 12
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: payment
        - secretRef:
            name: payment
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
  # servicer labels
  labels:
    project: roboshop
    tier: backend
    component: payment
spec:
  # Service uses the below labels to select the pods
  selector:
    project: roboshop
    tier: backend
    component: payment
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port