apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  # labels related to deployment resource
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: backend
      component: catalogue
  # Pod
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: catalogue
    spec:
      containers:
      - name: catalogue
        image: joindevops/catalogue:4.0.0
        envFrom:
        - configMapRef:
            name: catalogue
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  # servicer labels
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
  # Service uses the below labels to select the pods
  selector:
    project: roboshop
    tier: backend
    component: catalogue
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port