apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data:
  MONGO: "true"
  REDIS_URL: 'redis://redis:6379'
  MONGO_URL: "mongodb://mongodb:27017/users"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: user
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: backend
      component: user
  # Pod
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: user
    spec:
      containers:
      - name: user
        image: joindevops/user:4.0.0
        envFrom:
        - configMapRef:
            name: user
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: user
spec:
  selector:
    project: roboshop
    tier: backend
    component: user
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port